# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  repository_dispatch:
    types:
      - api
  push:
    branches: 
      - main
  schedule:
  # 定时任务，在每天的0点执行
    - cron: '0 0 * * *'
  # Triggers the workflow on push or pull request events but only for the main branch

jobs:
  update-uasier:
    runs-on: self-hosted
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      # - name: 'Set up Python'
      #   uses: actions/setup-python@v1
      #   with:
      #     python-version: 3.7
      # - name: 'Install requirements'
      #   run: pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple
      - name: 'Working'
        env:
          DIDA365_COOKIE: ${{ secrets.DIDA365_COOKIE }}
          CORPID: ${{ secrets.CORPID }}
          AGENTID: ${{ secrets.AGENTID }}
          CORPSECRET: ${{ secrets.CORPSECRET }}
        run: python main.py